### PR TITLE
Allow users to set apache vhost state

### PR DESCRIPTION
**Pull request by pecharmin**
This PR allows users to set the state of the apache vhost for mrepo when using this module. Currently the vhost is always present.
Some users may already include the apache module or like to configure the mrepo webservice by their own.

### CODE REVIEW

**Comment by bastelfreak** [comment]
thanks for the patch @pecharmin ! Can you add a unit test that verifies that the new parameter is working?

**Comment by pecharmin** [comment]
@bastelfreak I'll supply unit tests sonn.

**Comment by bastelfreak** [comment]
Hey @pecharmin, are you still interested in this PR?

**Comment by bastelfreak** [comment]
Hi @pecharmin, I' am  going to close this PR. Please reopen it if you're still interested in it.

**Pull request closed without merging**
